version: 2.1

orbs:
  discord: teka23/discord@0.0.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true
          
      - add_ssh_keys:
          fingerprints:
            - "f7:5a:16:a8:cb:b1:d5:96:f0:98:be:d7:51:c3:35:ea"

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t avabin/pierogiesbot:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push avabin/pierogiesbot:$TAG
          echo "Connecting to server..."
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "sh ~/start.sh $TAG"
      - discord/status:
          fail_only: false
